---
- name: "apt-get update"
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: "install nginx"
  apt:
    name: ['nginx']
    state: latest
  become: yes


- name: "copy custom index.html file"
  copy:
    src: index.html
    dest: /var/www/html/
    owner: root
    group: root
    mode: 0755

- name: "start nginx service"
  systemd: name=nginx state=started enabled=yes
